// Generated by build-console.mjs. No reads/writes occur until an API method is called.
(() => {
// Standalone backup format. No imports from the application and no network calls.
const FORMAT = 'notes-stage0-snapshot';

function canonical(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  return `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}`;
}

async function sha256(value) {
  const bytes = typeof value === 'string' ? new TextEncoder().encode(value) : value;
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest), x => x.toString(16).padStart(2, '0')).join('');
}

function base64(bytes) {
  let text = '';
  for (let i = 0; i < bytes.length; i += 8192) text += String.fromCharCode(...bytes.subarray(i, i + 8192));
  return btoa(text);
}

function unbase64(text) {
  const bytes = Uint8Array.from(atob(text), c => c.charCodeAt(0));
  if (base64(bytes) !== text) throw new Error('Non-canonical binary encoding');
  return bytes;
}

// Tagged values preserve undefined, special numbers and binary types without collisions
// with user objects. Unsupported types fail loudly instead of silently dropping data.
async function encode(value) {
  if (value === undefined) return ['undefined'];
  if (value === null) return ['null'];
  if (typeof value === 'string' || typeof value === 'boolean') return [typeof value, value];
  if (typeof value === 'number') return ['number', Object.is(value, -0) ? '-0' : String(value)];
  if (typeof value === 'bigint') return ['bigint', String(value)];
  if (value instanceof Date) return ['date', value.toISOString()];
  if (value instanceof File) return ['file', value.type, value.name, value.lastModified, base64(new Uint8Array(await value.arrayBuffer()))];
  if (value instanceof Blob) return ['blob', value.type, base64(new Uint8Array(await value.arrayBuffer()))];
  if (value instanceof ArrayBuffer) return ['buffer', base64(new Uint8Array(value))];
  if (ArrayBuffer.isView(value)) return ['view', value.constructor.name, base64(new Uint8Array(value.buffer, value.byteOffset, value.byteLength))];
  if (Array.isArray(value)) return ['array', await Promise.all(value.map(encode))];
  if (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null) {
    return ['object', await Promise.all(Object.keys(value).sort().map(async key => [key, await encode(value[key])]))];
  }
  throw new Error('Unsupported backup value type');
}

function decode(value) {
  if (!Array.isArray(value)) throw new Error('Invalid encoded value');
  const [tag, a, b, c, d] = value;
  switch (tag) {
    case 'undefined': return undefined;
    case 'null': return null;
    case 'string': if (typeof a !== 'string') break; return a;
    case 'boolean': if (typeof a !== 'boolean') break; return a;
    case 'number': if (typeof a !== 'string' || !['NaN', 'Infinity', '-Infinity', '-0'].includes(a) && String(Number(a)) !== a) break; return Number(a);
    case 'bigint': return BigInt(a);
    case 'date': return new Date(a);
    case 'blob': return new Blob([unbase64(b)], { type: a });
    case 'file': return new File([unbase64(d)], b, { type: a, lastModified: c });
    case 'buffer': return unbase64(a).buffer;
    case 'view': {
      const allowed = ['Uint8Array', 'Uint8ClampedArray', 'Int8Array', 'Uint16Array', 'Int16Array', 'Uint32Array', 'Int32Array', 'Float32Array', 'Float64Array', 'BigInt64Array', 'BigUint64Array', 'DataView'];
      if (!allowed.includes(a)) break;
      return new globalThis[a](unbase64(b).buffer);
    }
    case 'array': return b === undefined && Array.isArray(a) ? a.map(decode) : invalid();
    case 'object': {
      if (!Array.isArray(a)) break;
      const result = {};
      const seen = new Set();
      for (const [key, item] of a) {
        if (typeof key !== 'string' || seen.has(key)) return invalid();
        seen.add(key);
        Object.defineProperty(result, key, { value: decode(item), enumerable: true, writable: true, configurable: true });
      }
      return result;
    }
  }
  return invalid();
}
function invalid() { throw new Error('Invalid backup value'); }

async function buildManifest(snapshot) {
  const stores = {};
  for (const store of snapshot.stores) {
    const records = [];
    for (const record of store.records) {
      const raw = decode(record.value);
      const item = { key: record.key, sha256: await sha256(canonical(record)) };
      if (raw && typeof raw === 'object' && typeof raw.id === 'string') item.id = raw.id;
      if (raw && typeof raw === 'object' && raw.deletedAt) item.inTrash = true;
      if (raw?.blob instanceof Blob) {
        item.binaryBytes = raw.blob.size;
        item.binarySha256 = await sha256(await raw.blob.arrayBuffer());
      }
      records.push(item);
    }
    stores[store.name] = { count: records.length, schemaSha256: await sha256(canonical(store.schema)), records };
  }
  return { algorithm: 'SHA-256', stores, contentSha256: await sha256(canonical({ version: snapshot.database.version, stores: snapshot.stores })) };
}

async function sealSnapshot(snapshot) {
  const body = { format: FORMAT, formatVersion: 1, ...snapshot };
  body.manifest = await buildManifest(body);
  body.archiveSha256 = await sha256(canonical(body));
  return body;
}

async function validateSnapshot(snapshot) {
  if (!snapshot || snapshot.format !== FORMAT || snapshot.formatVersion !== 1 || !snapshot.database || !Number.isInteger(snapshot.database.version) || snapshot.database.version < 1 || !Array.isArray(snapshot.stores) || !snapshot.stores.length) throw new Error('Invalid or unsupported snapshot');
  const names = new Set();
  for (const store of snapshot.stores) {
    if (!store || typeof store.name !== 'string' || names.has(store.name) || !store.schema || !Array.isArray(store.schema.indexes) || !Array.isArray(store.records)) throw new Error('Invalid store schema');
    names.add(store.name);
    const keys = new Set();
    for (const record of store.records) {
      const key = canonical(record.key);
      if (keys.has(key)) throw new Error('Duplicate record key');
      keys.add(key);
      decode(record.key); decode(record.value);
    }
  }
  const { archiveSha256, ...body } = snapshot;
  if (await sha256(canonical(body)) !== archiveSha256) throw new Error('Archive checksum mismatch');
  if (canonical(await buildManifest(snapshot)) !== canonical(snapshot.manifest)) throw new Error('Manifest mismatch');
  return snapshot.manifest;
}

function inspectRelations(snapshot) {
  const data = Object.fromEntries(snapshot.stores.map(s => [s.name, s.records.map(r => decode(r.value))]));
  const issues = [];
  for (const [child, field, parent] of [['sections', 'notebookId', 'notebooks'], ['pages', 'sectionId', 'sections'], ['strokes', 'pageId', 'pages'], ['shapes', 'pageId', 'pages'], ['textBlocks', 'pageId', 'pages'], ['assets', 'pageId', 'pages']]) {
    const ids = new Set((data[parent] || []).map(r => r.id));
    for (const record of data[child] || []) if (record[field] && !ids.has(record[field])) issues.push({ store: child, id: record.id, field, missingId: record[field] });
  }
  const assets = new Set((data.assets || []).map(a => a.id));
  for (const block of data.textBlocks || []) {
    for (const match of String(block.contentHTML || '').matchAll(/data-asset-id\s*=\s*["']([^"']+)["']/g)) if (!assets.has(match[1])) issues.push({ store: 'textBlocks', id: block.id, missingAsset: match[1] });
  }
  return issues;
}


function requestResult(request) {
  return new Promise((resolve, reject) => {
    request.onsuccess = () => resolve(request.result);
    request.onerror = () => reject(new Error(`IndexedDB request failed: ${request.error?.name || 'unknown'}`));
  });
}
function transactionDone(tx) {
  return new Promise((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onabort = () => reject(new Error(`IndexedDB transaction aborted: ${tx.error?.name || 'unknown'}`));
    tx.onerror = () => {}; // Abort supplies the final error.
  });
}

async function openExisting(name) {
  // Opening without a version avoids upgrades. Abort creation if DB is absent.
  const request = indexedDB.open(name);
  request.onupgradeneeded = () => request.transaction.abort();
  const db = await requestResult(request);
  db.onversionchange = () => db.close();
  return db;
}

async function captureIndexedDB(name = 'onenote_clone_db') {
  const db = await openExisting(name);
  try {
    const names = Array.from(db.objectStoreNames).sort();
    if (!names.length) throw new Error('Database has no stores');
    // Enqueue ALL reads synchronously in ONE readonly transaction. Do not await
    // Blob encoding/hashing while IDB is active; those happen after tx completes.
    const tx = db.transaction(names, 'readonly');
    const done = transactionDone(tx);
    done.catch(() => {}); // Still awaited below; avoids unhandled rejection on a failed read.
    const pending = names.map(name => {
      const store = tx.objectStore(name);
      const schema = { keyPath: store.keyPath, autoIncrement: store.autoIncrement, indexes: Array.from(store.indexNames).sort().map(name => {
        const index = store.index(name);
        return { name, keyPath: index.keyPath, unique: index.unique, multiEntry: index.multiEntry };
      }) };
      return { name, schema, keys: requestResult(store.getAllKeys()), values: requestResult(store.getAll()) };
    });
    const raw = await Promise.all(pending.map(async store => ({ name: store.name, schema: store.schema, keys: await store.keys, values: await store.values })));
    await done;
    const stores = [];
    for (const store of raw) {
      const records = [];
      for (let i = 0; i < store.keys.length; i++) records.push({ key: await encode(store.keys[i]), value: await encode(store.values[i]) });
      stores.push({ name: store.name, schema: store.schema, records });
    }
    const snapshot = await sealSnapshot({ kind: 'indexeddb', createdAt: new Date().toISOString(), source: { origin: location.origin, persistedOnly: true, inMemoryEditsIncluded: false }, database: { name: db.name, version: db.version }, stores });
    await validateSnapshot(snapshot);
    return { snapshot, relationIssues: inspectRelations(snapshot) };
  } finally { db.close(); }
}

async function downloadIndexedDB(name = 'onenote_clone_db') {
  const result = await captureIndexedDB(name);
  const blob = new Blob([JSON.stringify(result.snapshot)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `notes-stage0-${new Date().toISOString().replace(/[:.]/g, '-')}.json`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 60000);
  return { manifest: result.snapshot.manifest, relationIssues: result.relationIssues, inMemoryEditsIncluded: false };
}

async function restoreTemporary(snapshot, name = `notes_stage0_restore_${crypto.randomUUID()}`) {
  await validateSnapshot(snapshot); // Validation always precedes opening/writing.
  if (snapshot.kind !== 'indexeddb' || !/^notes_stage0_restore_[a-zA-Z0-9_-]+$/.test(name) || name === snapshot.database.name) throw new Error('Restore is allowed only into a NEW temporary database');
  if (snapshot.stores.some(s => s.schema.autoIncrement)) throw new Error('Auto-increment generator state cannot be verified by readonly capture; review this store separately');
  // Decode all values before opening the write transaction.
  const stores = snapshot.stores.map(s => ({ ...s, decoded: s.records.map(r => ({ key: decode(r.key), value: decode(r.value) })) }));
  let created = false;
  const request = indexedDB.open(name, snapshot.database.version);
  request.onupgradeneeded = event => {
    if (event.oldVersion !== 0) { request.transaction.abort(); return; }
    created = true;
    for (const source of stores) {
      const store = request.result.createObjectStore(source.name, { keyPath: source.schema.keyPath, autoIncrement: source.schema.autoIncrement });
      for (const index of source.schema.indexes) store.createIndex(index.name, index.keyPath, { unique: index.unique, multiEntry: index.multiEntry });
    }
  };
  const db = await requestResult(request);
  try {
    if (!created) throw new Error('Refusing to overwrite an existing database');
    const tx = db.transaction(stores.map(s => s.name), 'readwrite', { durability: 'strict' });
    const done = transactionDone(tx);
    done.catch(() => {});
    try {
      for (const source of stores) {
        const store = tx.objectStore(source.name);
        for (const record of source.decoded) {
          if (source.schema.keyPath === null) store.add(record.value, record.key);
          else store.add(record.value);
        }
      }
    } catch (error) { tx.abort(); await done.catch(() => {}); throw error; }
    await done;
  } finally { db.close(); }
  const restored = await captureIndexedDB(name);
  if (restored.snapshot.manifest.contentSha256 !== snapshot.manifest.contentSha256) throw new Error('Restored snapshot differs from source');
  return { name, verified: true, manifest: restored.snapshot.manifest, relationIssues: restored.relationIssues };
}

globalThis.NotesStage0 = Object.freeze({ captureIndexedDB, downloadIndexedDB, restoreTemporary, validateSnapshot, inspectRelations });
console.info('NotesStage0 ready. Export only persisted data: await NotesStage0.downloadIndexedDB()');
})();
