import { readFile, writeFile } from 'node:fs/promises';
const core = await readFile(new URL('./backup-core.mjs', import.meta.url), 'utf8');
const db = await readFile(new URL('./indexeddb-backup.mjs', import.meta.url), 'utf8');
const body = `${core}\n${db.replace(/^import .*;\r?\n/m, '')}`.replace(/^export /gm, '');
await writeFile(new URL('./backup-console.js', import.meta.url), `// Generated by build-console.mjs. No reads/writes occur until an API method is called.\n(() => {\n${body}\nglobalThis.NotesStage0 = Object.freeze({ captureIndexedDB, downloadIndexedDB, restoreTemporary, validateSnapshot, inspectRelations });\nconsole.info('NotesStage0 ready. Export only persisted data: await NotesStage0.downloadIndexedDB()');\n})();\n`);
console.log('Built standalone console tool (no application imports).');
